const GeoLayout ttm_area_1_geo_0E000A70[] = {
    GEO_NODE_SCREEN_AREA(10, 160, 120, 160, 120),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND(0x0000, geo_skybox_main),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM_WITH_FUNC(45, 100, 12800, geo_camera_fov),
            GEO_OPEN_NODE(),
                GEO_CAMERA(1, 0, 2000, 6000, 0, -2200, 0, geo_camera_main),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_area_1_dl_0700A120),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_area_1_dl_0700A2E0),
                    GEO_RENDER_OBJ(),
                    GEO_ASM(0, geo_painting_update),
                    GEO_ASM(512, geo_painting_draw),
                    GEO_ASM(0, geo_movtex_pause_control),
                    GEO_ASM(13825, geo_movtex_draw_nocolor),
                    GEO_ASM(13826, geo_movtex_draw_nocolor),
                    GEO_ASM(13827, geo_movtex_draw_nocolor),
                    GEO_ASM(13828, geo_movtex_draw_nocolor),
                    GEO_ASM(13829, geo_movtex_draw_nocolor),
                    GEO_ASM(13825, geo_movtex_draw_water_regions),
                    GEO_ASM(0, geo_envfx_main),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_cannon_circle_base),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
