const GeoLayout ccm_area_2_geo_0E0005F8[] = {
    GEO_NODE_SCREEN_AREA(10, 160, 120, 160, 120),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND_COLOR(0x0001),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM_WITH_FUNC(45, 100, 12800, geo_camera_fov),
            GEO_OPEN_NODE(),
                GEO_CAMERA(9, 0, 2000, 6000, 0, 0, 0, geo_camera_main),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_area_2_dl_0701CE30),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_area_2_dl_0701E558),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, ccm_area_2_dl_0701E6B0),
                    GEO_DISPLAY_LIST(LAYER_ALPHA, ccm_area_2_dl_0701FC78),
                    GEO_DISPLAY_LIST(LAYER_ALPHA, ccm_area_2_dl_0701FD78),
                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_area_2_dl_0701FE60),
                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_area_2_dl_070207F0),
                    GEO_RENDER_OBJ(),
                    GEO_ASM(0, geo_envfx_main),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
