const GeoLayout jrb_area_1_geo_0E000A18[] = {
    GEO_NODE_SCREEN_AREA(10, 160, 120, 160, 120),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND(0x0008, geo_skybox_main),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM_WITH_FUNC(45, 100, 25000, geo_camera_fov),
            GEO_OPEN_NODE(),
                GEO_CAMERA(16, 0, 2000, 6000, 0, 0, 0, geo_camera_main),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_area_1_dl_07002FD0),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_area_1_dl_07004940),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_area_1_dl_07004C78),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_area_1_dl_070058C8),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_area_1_dl_070069B0),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_area_1_dl_07007570),
                    GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_area_1_dl_07007718),
                    GEO_ASM(0, geo_movtex_pause_control),
                    GEO_ASM(4609, geo_movtex_draw_water_regions),
                    GEO_ASM(4613, geo_movtex_draw_water_regions),
                    GEO_RENDER_OBJ(),
                    GEO_ASM(14, geo_envfx_main),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_cannon_circle_base),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
