const GeoLayout bowser_1_geo_0D0000D8[] = {
    GEO_SHADOW(SHADOW_CIRCLE_9_VERTS, 155, 400),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_06040290),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, -89, -2, -18, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 69, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_0603D280),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_0603E738),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -32, -112, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_060437E8),
                    GEO_ASM(0, geo_update_projectile_pos_from_parent),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 118, 67, 105, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 49, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_0603B208),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_060399D8),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_060392E0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 136, 130, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 61, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, -13, 258, 0, bowser_1_dl_06043340),
                    GEO_CLOSE_NODE(),
                    GEO_SWITCH_CASE(9, geo_switch_bowser_eyes),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_06042498),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_060424F0),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_06042548),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_060425A0),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_060425F8),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_06042650),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_060426A8),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_06042700),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_06042758),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, -118, 67, 105, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 49, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_0603E030),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_0603C750),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_0603C048),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 89, -2, -18, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 69, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_0603A4E8),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_1_dl_0603B8D0),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout bowser_1_geo_0D000424[] = {
    GEO_SHADOW(SHADOW_CIRCLE_9_VERTS, 155, 400),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_06040358),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, -89, -2, -18, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 69, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603D280),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603E738),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, -32, -112, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_060437E8),
                    GEO_ASM(0, geo_update_projectile_pos_from_parent),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 118, 67, 105, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 49, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603B208),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_060399D8),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_060392E0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 136, 130, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 61, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, -13, 258, 0, bowser_1_dl_06043340),
                    GEO_CLOSE_NODE(),
                    GEO_SWITCH_CASE(9, geo_switch_bowser_eyes),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_06042498),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_060424F0),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_06042548),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_060425A0),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_060425F8),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_06042650),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_060426A8),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_06042700),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_06042758),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, -118, 67, 105, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 49, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603E030),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603C750),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603C048),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, -2, -18, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 69, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603A4E8),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603B948),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout bowser_1_geo_0D000AB8[] = {
    GEO_SHADOW(SHADOW_CIRCLE_9_VERTS, 155, 400),
    GEO_RETURN(),
};


const GeoLayout bowser_1_geo_0D000AC4[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ASM(0, geo_update_layer_transparency),
        GEO_SWITCH_CASE(3, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_NODE_START(),
            GEO_OPEN_NODE(),
                GEO_ASM(0, geo_bits_bowser_coloring),
                GEO_BRANCH(1, bowser_1_geo_0D0000D8),
            GEO_CLOSE_NODE(),
            GEO_NODE_START(),
            GEO_OPEN_NODE(),
                GEO_ASM(0, geo_bits_bowser_coloring),
                GEO_BRANCH(1, bowser_1_geo_0D000424),
            GEO_CLOSE_NODE(),
            GEO_NODE_START(),
            GEO_OPEN_NODE(),
                GEO_ASM(0, geo_bits_bowser_coloring),
                GEO_BRANCH(1, bowser_1_geo_0D000AB8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bowser_1_geo_0D000BBC[] = {
    GEO_CULLING_RADIUS(1000),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00030000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_1_dl_0605AB10),
            GEO_BILLBOARD(),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, bowser_1_dl_0605A980),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bowser_1_geo_0D000BFC[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ASM(0, geo_update_layer_transparency),
        GEO_SWITCH_CASE(5, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_06062C88),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_06062D28),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_06062DC8),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_06062E68),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_06062D28),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bowser_1_geo_0D000000[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(14, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_0601C108),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_0601C1A8),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_0601C248),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_0601C2E8),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_0601C388),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_0601C428),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_0601C4C8),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_0601C568),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_0601C608),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_0601C6A8),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_0601C748),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_0601C7E8),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_0601C888),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_1_dl_0601C928),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bowser_1_geo_0D000090[] = {
    GEO_CULLING_RADIUS(10000),
    GEO_OPEN_NODE(),
        GEO_ASM(20, geo_update_layer_transparency),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bowser_1_dl_0601EAC0),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bowser_1_geo_0D000770[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_06040358),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, -89, -2, -18, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 69, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603D280),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603E738),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, -32, -112, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_060437E8),
                    GEO_ASM(0, geo_update_projectile_pos_from_parent),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 118, 67, 105, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 49, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603B208),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_060399D8),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_060392E0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 136, 130, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 61, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, -13, 258, 0, bowser_1_dl_06043340),
                    GEO_CLOSE_NODE(),
                    GEO_SWITCH_CASE(9, geo_switch_bowser_eyes),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_06042498),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_060424F0),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_06042548),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_060425A0),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_060425F8),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_06042650),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_060426A8),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_06042700),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_06042758),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, -118, 67, 105, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 49, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603E030),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603C750),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603C048),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, -2, -18, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 69, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603A4E8),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_1_dl_0603B948),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout bowser_1_geo_0D000B40[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ASM(0, geo_update_layer_transparency),
        GEO_SWITCH_CASE(3, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_NODE_START(),
            GEO_OPEN_NODE(),
                GEO_ASM(0, geo_bits_bowser_coloring),
                GEO_BRANCH(1, bowser_1_geo_0D0000D8),
            GEO_CLOSE_NODE(),
            GEO_NODE_START(),
            GEO_OPEN_NODE(),
                GEO_ASM(0, geo_bits_bowser_coloring),
                GEO_BRANCH(1, bowser_1_geo_0D000770),
            GEO_CLOSE_NODE(),
            GEO_NODE_START(),
            GEO_OPEN_NODE(),
                GEO_ASM(0, geo_bits_bowser_coloring),
                GEO_BRANCH(1, bowser_1_geo_0D000AB8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bowser_1_geo_0D0000B0[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_BILLBOARD(),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bowser_1_dl_0601F3C0),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
