const GeoLayout sl_area_1_geo_0E0003A8[] = {
    GEO_NODE_SCREEN_AREA(10, 160, 120, 160, 120),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND(0x0004, geo_skybox_main),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM_WITH_FUNC(45, 100, 20000, geo_camera_fov),
            GEO_OPEN_NODE(),
                GEO_CAMERA(16, 0, 2000, 6000, 0, 4400, 0, geo_camera_main),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_area_1_dl_07005478),
                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sl_area_1_dl_070056B0),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_area_1_dl_070073D0),
                    GEO_DISPLAY_LIST(LAYER_ALPHA, sl_area_1_dl_07007880),
                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sl_area_1_dl_070088B0),
                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, sl_area_1_dl_07008D58),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_area_1_dl_0700A5A0),
                    GEO_ASM(0, geo_movtex_pause_control),
                    GEO_ASM(4097, geo_movtex_draw_water_regions),
                    GEO_RENDER_OBJ(),
                    GEO_ASM(1, geo_envfx_main),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_cannon_circle_base),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
