-- Moving Textures (WaterBoxes)
--   Every movtext type is set to 1 (normal water texture)
--   If you want to configure and setup other water type, change the value here
movtexqc_register('castle_inside_1_Movtex_0', 6, 1, 0)
movtexqc_register('castle_inside_1_Movtex_1', 6, 1, 0)
movtexqc_register('castle_inside_1_Movtex_2', 6, 1, 0)
movtexqc_register('castle_grounds_1_Movtex_0', 16, 1, 0)
movtexqc_register('castle_grounds_1_Movtex_1', 16, 1, 0)
movtexqc_register('castle_grounds_1_Movtex_2', 16, 1, 0)
movtexqc_register('bitdw_1_Movtex_0', 17, 1, 0)
movtexqc_register('bitdw_1_Movtex_1', 17, 1, 0)
movtexqc_register('bitdw_1_Movtex_2', 17, 1, 0)
movtexqc_register('bitfs_1_Movtex_0', 19, 1, 0)
movtexqc_register('bitfs_1_Movtex_1', 19, 1, 0)
movtexqc_register('bitfs_1_Movtex_2', 19, 1, 0)
movtexqc_register('bits_1_Movtex_0', 21, 1, 0)
movtexqc_register('bits_1_Movtex_1', 21, 1, 0)
movtexqc_register('bits_1_Movtex_2', 21, 1, 0)
movtexqc_register('castle_courtyard_1_Movtex_0', 26, 1, 0)
movtexqc_register('castle_courtyard_1_Movtex_1', 26, 1, 0)
movtexqc_register('castle_courtyard_1_Movtex_2', 26, 1, 0)
movtexqc_register('wmotr_1_Movtex_0', 31, 1, 0)
movtexqc_register('wmotr_1_Movtex_1', 31, 1, 0)
movtexqc_register('wmotr_1_Movtex_2', 31, 1, 0)
