const GeoLayout ssl_area_1_geo_0E000648[] = {
    GEO_NODE_SCREEN_AREA(10, 160, 120, 160, 120),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND(0x0005, geo_skybox_main),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM_WITH_FUNC(45, 100, 20000, geo_camera_fov),
            GEO_OPEN_NODE(),
                GEO_CAMERA(1, 0, 2000, 6000, -2048, 0, -1024, geo_camera_main),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, ssl_area_1_dl_07009F48),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, ssl_area_1_dl_0700BA78),
                    GEO_DISPLAY_LIST(LAYER_ALPHA, ssl_area_1_dl_0700BC18),
                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, ssl_area_1_dl_0700BD00),
                    GEO_ASM(2049, geo_movtex_update_horizontal),
                    GEO_ASM(0, geo_movtex_pause_control),
                    GEO_ASM(2049, geo_movtex_draw_water_regions),
                    GEO_ASM(2129, geo_movtex_draw_water_regions),
                    GEO_ASM(2049, geo_movtex_draw_colored),
                    GEO_ASM(2050, geo_movtex_draw_colored),
                    GEO_ASM(2051, geo_movtex_draw_colored),
                    GEO_RENDER_OBJ(),
                    GEO_ASM(0, geo_envfx_main),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_cannon_circle_base),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
