const GeoLayout bbh_geo_0F000000[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_08000E08),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000028[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 200, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_08002C88),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(2, geo_switch_anim_state),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                            GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_08002BA0),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(2, geo_switch_anim_state),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                            GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_08002BA0),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(2, geo_switch_anim_state),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                            GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_08002BA0),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(2, geo_switch_anim_state),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                            GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_08002BA0),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_08002D70),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_BILLBOARD(),
                    GEO_OPEN_NODE(),
                        GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_08002E58),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0004CC[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_0800C718),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0004E4[] = {
    GEO_CULLING_RADIUS(400),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_0800D680),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0005D0[] = {
    GEO_CULLING_RADIUS(500),
    GEO_OPEN_NODE(),
        GEO_SHADOW(SHADOW_SQUARE_PERMANENT, 180, 240),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(2, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_08012D20),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_08012D48),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000610[] = {
    GEO_CULLING_RADIUS(500),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(2, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_08012D20),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_08012D48),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000A58[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_SHADOW(SHADOW_SQUARE_PERMANENT, 180, 70),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(4, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_08024F88),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_08024FA8),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_08024FC8),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_08024FE8),
            GEO_CLOSE_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_080259F8),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000694[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_SHADOW(SHADOW_SQUARE_PERMANENT, 180, 70),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(4, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_08019318),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_08019378),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_080193D8),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_08019438),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0006E4[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_0801D760),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_BILLBOARD(),
                    GEO_OPEN_NODE(),
                        GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_0801B690),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_OPEN_NODE(),
                    GEO_SWITCH_CASE(2, geo_switch_anim_state),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 48, 0, 0, bbh_dl_0801B5C8),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 48, 0, 0, bbh_dl_0801B5F0),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -60, -16, 45, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_0801CE20),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -60, -16, -45, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_0801CF78),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000AB0[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 200, 70),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00010000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_08028B78),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000A30[] = {
    GEO_CULLING_RADIUS(500),
    GEO_OPEN_NODE(),
        GEO_SHADOW(SHADOW_SQUARE_PERMANENT, 180, 70),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_08024BB8),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0007B8[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 200, 70),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00006000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BILLBOARD(),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_08022D08),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 57, -60, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 91, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_08023270),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 55, 62, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 91, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_08023378),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_08023480),
                    GEO_SWITCH_CASE(2, geo_switch_anim_state),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_08022B58),
                        GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_08022B88),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0008F4[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 200, 70),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00006000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BILLBOARD(),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_08022D78),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 57, -60, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 91, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_08023270),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 55, 62, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 91, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_08023378),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_08023480),
                    GEO_SWITCH_CASE(2, geo_switch_anim_state),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_08022B58),
                        GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_08022B88),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000640[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 200, 280),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00029999),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_08022D08),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0001C0[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_08006660),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0001A8[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_080057F8),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0004FC[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 100, 100),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_0800DFE0),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000518[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_08011710),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -45, -20, -55, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_08010840),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -45, -20, 55, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_08010968),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 250, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bbh_dl_08010B80),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0001D8[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 281, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_0800ABE8),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 113, -152, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 74, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_ANIMATED_PART(LAYER_OPAQUE, 96, 0, 0, NULL),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                            GEO_OPEN_NODE(),
                                                GEO_BILLBOARD(),
                                                GEO_OPEN_NODE(),
                                                    GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_0800A5F8),
                                                GEO_CLOSE_NODE(),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_0800A998),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_0800A758),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_BILLBOARD(),
                                GEO_OPEN_NODE(),
                                    GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_0800A068),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 1, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 209, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                        GEO_OPEN_NODE(),
                                            GEO_BILLBOARD(),
                                            GEO_OPEN_NODE(),
                                                GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_0800A1D0),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                            GEO_OPEN_NODE(),
                                                GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, NULL),
                                                GEO_OPEN_NODE(),
                                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                                    GEO_OPEN_NODE(),
                                                        GEO_BILLBOARD(),
                                                        GEO_OPEN_NODE(),
                                                            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_0800A428),
                                                        GEO_CLOSE_NODE(),
                                                    GEO_CLOSE_NODE(),
                                                GEO_CLOSE_NODE(),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 1, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 209, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                        GEO_OPEN_NODE(),
                                            GEO_BILLBOARD(),
                                            GEO_OPEN_NODE(),
                                                GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_0800A338),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                            GEO_OPEN_NODE(),
                                                GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, NULL),
                                                GEO_OPEN_NODE(),
                                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                                    GEO_OPEN_NODE(),
                                                        GEO_BILLBOARD(),
                                                        GEO_OPEN_NODE(),
                                                            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_0800A510),
                                                        GEO_CLOSE_NODE(),
                                                    GEO_CLOSE_NODE(),
                                                    GEO_ASM(0, geo_update_projectile_pos_from_parent),
                                                GEO_CLOSE_NODE(),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_0800A8D0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F00066C[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00029999),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_08022D08),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0C000224[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 70),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00006666),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_update_layer_transparency),
            GEO_SWITCH_CASE(2, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_0500C1B0),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_0500C1B0),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0C000188[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 80),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_05006A68),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0C0000D8[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_05005190),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -7, -9, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_05005680),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 156, -9, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_05005408),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -3, 17, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_05004EE8),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0C0001B4[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_050098E8),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -141, -546, 218, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_05008CB0),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0C000000[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_05001F98),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_05001B20),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_05002140),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_05001D68),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_05001978),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_050022E0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0C0000C0[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_05002FB0),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0C000274[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_SHADOW(SHADOW_CIRCLE_9_VERTS, 150, 100),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_0500F7D8),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_0500FC28),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_05010100),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0D0000DC[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_BILLBOARD(),
                    GEO_OPEN_NODE(),
                        GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_06006880),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, bbh_dl_06006758),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, bbh_dl_06006A88),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 57, -48, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06006BD0),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 57, -48, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06006D00),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0D000394[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -29, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 113, 112, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 198, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 195, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06014378),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06014270),
                            GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06014188),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 109, -116, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 198, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 195, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06014378),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06014270),
                            GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06014188),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BILLBOARD(),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060139F8),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -29, -57, 28, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 158, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD(),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_06013AE8),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06013CB8),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -29, 55, 28, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 157, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD(),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_06013BD0),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06013DA0),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -116, -111, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 198, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 195, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06014378),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06014270),
                            GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06014188),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -116, 112, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 195, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 199, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06014378),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06014270),
                            GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bbh_dl_06014188),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_060140F0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0D00001C[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(20, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060041F0),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_06004208),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_06004220),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_06004208),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060041F0),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060041F0),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_06004208),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_06004220),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_06004208),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060041F0),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_060041D8),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0D000000[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 155, 200),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_06002080),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0D000230[] = {
    GEO_CULLING_RADIUS(5000),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_0600CFD0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 1295, 0, 0, bbh_dl_0600C8B8),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 916, 0, 0, bbh_dl_0600C468),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 874, 0, 0, bbh_dl_0600BAF8),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_0600DFA8),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 30, 444, -6, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_0600C030),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -893, -490, -6, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_0600D440),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 1300, 0, 0, bbh_dl_0600D6D8),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -1086, 91, -700, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_0600DE38),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 902, 700, -785, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_0600DA88),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -1086, 91, 698, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_0600DC60),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 902, 700, 783, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_0600D8B0),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0D0001A0[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_snufit_move_mask),
            GEO_TRANSLATE_NODE(LAYER_FORCE, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_06009748),
            GEO_CLOSE_NODE(),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_06009498),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_06009938),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_06009B68),
            GEO_BILLBOARD(),
            GEO_OPEN_NODE(),
                GEO_ASM(0, geo_snufit_scale_body),
                GEO_SCALE(LAYER_FORCE, 0x00000000),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_06009A10),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_16000720[] = {
    GEO_TRANSLATE_NODE(LAYER_FORCE, 78, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, -300, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_OPEN_NODE(),
                    GEO_RENDER_RANGE(-2048, 3500),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_03014D40),
                    GEO_CLOSE_NODE(),
                    GEO_RENDER_RANGE(3500, 32767),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bbh_dl_03015158),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0E0005B0[] = {
    GEO_CULLING_RADIUS(700),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_0701F2E8),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0E0005C8[] = {
    GEO_CULLING_RADIUS(600),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_0701F5F8),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0E0005E0[] = {
    GEO_CULLING_RADIUS(650),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_0701F7E8),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0E0005F8[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_0701FAB0),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0E000610[] = {
    GEO_CULLING_RADIUS(1000),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_0701FD28),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0E000628[] = {
    GEO_CULLING_RADIUS(600),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_0701FFE8),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0E000640[] = {
    GEO_CULLING_RADIUS(2300),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_070202F0),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0E000658[] = {
    GEO_CULLING_RADIUS(800),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_070206F0),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
