extern const GeoLayout lethalramp_geo[];
extern Lights1 lethalramp_f3dlite_material_003_lights;
extern Lights1 lethalramp_f3dlite_material_004_lights;
extern u8 lethalramp__0900B800_rgba16[];
extern u8 lethalramp__09007800_rgba16[];
extern Vtx lethalramp_lethalramp_mesh_layer_1_vtx_0[12];
extern Gfx lethalramp_lethalramp_mesh_layer_1_tri_0[];
extern Vtx lethalramp_lethalramp_mesh_layer_1_vtx_1[20];
extern Gfx lethalramp_lethalramp_mesh_layer_1_tri_1[];
extern Gfx mat_lethalramp_f3dlite_material_003[];
extern Gfx mat_lethalramp_f3dlite_material_004[];
extern Gfx lethalramp_lethalramp_mesh_layer_1[];
