const GeoLayout castle_courtyard_geo_0C000000[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_05000670),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -12, 37, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_05000528),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -12, -37, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_05000600),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_05000598),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_courtyard_geo_0C000098[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_05007230),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, castle_courtyard_dl_05006A18),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(8, NULL),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_05005CE0),
                            GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_05005D38),
                            GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_05005D90),
                            GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_05005DE8),
                            GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_05005E40),
                            GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_05005E98),
                            GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_05005EF0),
                            GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_05005F48),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 38, -78, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_05007B18),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, castle_courtyard_dl_050091A8),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, castle_courtyard_dl_05008F80),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 84, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_05007EB8),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 104, 0, 0, castle_courtyard_dl_05008808),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, castle_courtyard_dl_05009560),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_050085C0),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, -84, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_05008288),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 104, 0, 0, castle_courtyard_dl_05008D58),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, castle_courtyard_dl_050099A0),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_05008B10),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, castle_courtyard_dl_050060E0),
                GEO_ANIMATED_PART(LAYER_OPAQUE, -23, -1, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_0500A108),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout castle_courtyard_geo_0C000254[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, castle_courtyard_dl_05007288),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, castle_courtyard_dl_05006A18),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 132, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(8, NULL),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_05005CE0),
                            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_05005D38),
                            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_05005D90),
                            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_05005DE8),
                            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_05005E40),
                            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_05005E98),
                            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_05005EF0),
                            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_05005F48),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 38, -78, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, castle_courtyard_dl_05007B18),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 132, 0, 0, castle_courtyard_dl_050091A8),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 132, 0, 0, castle_courtyard_dl_05008F80),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 84, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, castle_courtyard_dl_05007EB8),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 104, 0, 0, castle_courtyard_dl_05008808),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, castle_courtyard_dl_05009560),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, castle_courtyard_dl_050085C0),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, -84, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, castle_courtyard_dl_05008288),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 104, 0, 0, castle_courtyard_dl_05008D58),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, castle_courtyard_dl_050099A0),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, castle_courtyard_dl_05008B10),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, castle_courtyard_dl_050060E0),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, -23, -1, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, castle_courtyard_dl_0500A188),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout castle_courtyard_geo_0C000410[] = {
    GEO_SHADOW(SHADOW_CIRCLE_9_VERTS, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ASM(10, geo_update_layer_transparency),
            GEO_SWITCH_CASE(2, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_BRANCH(1, castle_courtyard_geo_0C000098),
                GEO_BRANCH(1, castle_courtyard_geo_0C000254),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_courtyard_geo_0C000468[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 200, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_050226F0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 100, 0, 0, castle_courtyard_dl_050224F0),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 222, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_SWITCH_CASE(2, geo_switch_anim_state),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_0501DA58),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_0501DA80),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 49, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_05021398),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 51, 55, 97, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_05021760),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 74, 0, 0, castle_courtyard_dl_050216C0),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 69, 0, 0, castle_courtyard_dl_05021578),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 51, 55, -97, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_050219E8),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 74, 0, 0, castle_courtyard_dl_05021948),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 69, 0, 0, castle_courtyard_dl_05021800),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 27, 95, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_05021DC0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 100, 0, 0, castle_courtyard_dl_05021C78),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, castle_courtyard_dl_05021A88),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -89, -62, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_05021F20),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 27, -95, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_courtyard_dl_05022390),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 100, 0, 0, castle_courtyard_dl_05022248),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, castle_courtyard_dl_05022058),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
