const GeoLayout ccm_geo_0C000000[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00008000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, ccm_dl_05002900),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 100, 0, 0, ccm_dl_05000328),
                    GEO_ANIMATED_PART(LAYER_ALPHA, 100, 0, 0, ccm_dl_05002A20),
                    GEO_ANIMATED_PART(LAYER_ALPHA, 100, 0, 0, ccm_dl_05002B30),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -88, -32, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ccm_dl_050002A0),
                        GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, ccm_dl_05002D08),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_BILLBOARD(),
                    GEO_OPEN_NODE(),
                        GEO_DISPLAY_LIST(LAYER_ALPHA, ccm_dl_05002748),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, ccm_dl_05002830),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ccm_geo_0C00021C[] = {
    GEO_SCALE(LAYER_FORCE, 0x00004000),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_BILLBOARD(),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_ALPHA, ccm_dl_0500C620),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 356, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_BILLBOARD(),
                    GEO_OPEN_NODE(),
                        GEO_DISPLAY_LIST(LAYER_ALPHA, ccm_dl_0500CBF8),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_ALPHA, 356, 0, 0, ccm_dl_0500CCE8),
                GEO_ANIMATED_PART(LAYER_ALPHA, 356, 0, 0, ccm_dl_0500C760),
                GEO_SWITCH_CASE(2, geo_switch_anim_state),
                GEO_OPEN_NODE(),
                    GEO_NODE_START(),
                    GEO_NODE_START(),
                    GEO_OPEN_NODE(),
                        GEO_SCALE(LAYER_FORCE, 0x00010000),
                        GEO_OPEN_NODE(),
                            GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 490, 14, 43, 305, 0, 248, dl_03022F48),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, -229, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ccm_dl_0500C500),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, ccm_dl_0500CAA8),
                        GEO_ASM(0, geo_update_projectile_pos_from_parent),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 356, 0, 0, NULL),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ccm_geo_0C000348[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 180, 160),
    GEO_OPEN_NODE(),
        GEO_BRANCH_AND_LINK(ccm_geo_0C00021C),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ccm_geo_0C000104[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 40, ccm_dl_05007540),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, -51, 84, -13, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ccm_dl_05007198),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 51, 84, -13, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ccm_dl_050071E8),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, -38, -54, -13, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ccm_dl_05007238),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 38, -54, -13, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ccm_dl_050072C8),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 111, -19, NULL),
                GEO_OPEN_NODE(),
                    GEO_SWITCH_CASE(5, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ccm_dl_05006428),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ccm_dl_05006458),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ccm_dl_05006488),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ccm_dl_050064B8),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ccm_dl_050064E8),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ccm_geo_12000390[] = {
    GEO_CULLING_RADIUS(350),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_0700A780),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ccm_geo_12000360[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_dl_0700A890),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ccm_geo_12000378[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_dl_0700A980),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
