extern const GeoLayout travis_cap_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout travis_cap_Normal_Cap_State_Switch_opt2[];
extern const GeoLayout travis_cap_Normal_Cap_State_Switch_opt3[];
extern const GeoLayout travis_cap_geo[];
extern Lights1 travis_cap_glasses_glass_lights;
extern u8 travis_cap_white_i8[];
extern u8 travis_cap__301CF50_ci8[];
extern u8 travis_cap__301CF50_pal_rgba16[];
extern u8 travis_cap_Metal_Shade_rgba16_rgba16[];
extern Vtx travis_cap_Normal_Cap_DL_mesh_layer_5_vtx_0[28];
extern Gfx travis_cap_Normal_Cap_DL_mesh_layer_5_tri_0[];
extern Vtx travis_cap_Normal_Cap_DL_mesh_layer_1_vtx_0[204];
extern Gfx travis_cap_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Gfx mat_travis_cap_glasses_glass[];
extern Gfx mat_revert_travis_cap_glasses_glass[];
extern Gfx mat_travis_cap_glasses_base[];
extern Gfx mat_revert_travis_cap_glasses_base[];
extern Gfx mat_travis_cap_Metal__METAL__001[];
extern Gfx mat_revert_travis_cap_Metal__METAL__001[];
extern Gfx travis_cap_Normal_Cap_DL_mesh_layer_5[];
extern Gfx travis_cap_Normal_Cap_DL_mesh_layer_5_mat_override_Metal__METAL__001_0[];
extern Gfx travis_cap_Normal_Cap_DL_mesh_layer_1[];
extern Gfx travis_cap_Normal_Cap_DL_mesh_layer_1_mat_override_Metal__METAL__001_0[];
