const GeoLayout castle_grounds_geo_0C000000[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_grounds_dl_05000670),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -12, 37, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_grounds_dl_05000528),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -12, -37, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_grounds_dl_05000600),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_grounds_dl_05000598),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_grounds_geo_0C000468[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 200, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_grounds_dl_050226F0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 100, 0, 0, castle_grounds_dl_050224F0),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 222, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_SWITCH_CASE(2, geo_switch_anim_state),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_0501DA58),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_0501DA80),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 49, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_grounds_dl_05021398),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 51, 55, 97, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_grounds_dl_05021760),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 74, 0, 0, castle_grounds_dl_050216C0),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 69, 0, 0, castle_grounds_dl_05021578),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 51, 55, -97, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_grounds_dl_050219E8),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 74, 0, 0, castle_grounds_dl_05021948),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 69, 0, 0, castle_grounds_dl_05021800),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 27, 95, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_grounds_dl_05021DC0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 100, 0, 0, castle_grounds_dl_05021C78),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, castle_grounds_dl_05021A88),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -89, -62, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_grounds_dl_05021F20),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 27, -95, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_grounds_dl_05022390),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 100, 0, 0, castle_grounds_dl_05022248),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, castle_grounds_dl_05022058),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_grounds_geo_0E0006F4[] = {
    GEO_CULLING_RADIUS(2100),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_0700A290),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_grounds_geo_0E00070C[] = {
    GEO_CULLING_RADIUS(15000),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_0700BB80),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_grounds_geo_0E000660[] = {
    GEO_CULLING_RADIUS(1000),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00006000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, castle_grounds_dl_0700C768),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 459, 0, 0, castle_grounds_dl_0700C728),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 460, 0, 0, castle_grounds_dl_0700C6E8),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 345, 0, 0, castle_grounds_dl_0700C6A8),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 287, 0, 0, castle_grounds_dl_0700C670),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_grounds_geo_0E000724[] = {
    GEO_CULLING_RADIUS(15000),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_0700BC68),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
