const GeoLayout bob_geo_0C000308[] = {
    GEO_CULLING_RADIUS(150),
    GEO_OPEN_NODE(),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bob_dl_05011000),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0C000328[] = {
    GEO_CULLING_RADIUS(150),
    GEO_OPEN_NODE(),
        GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 100, 160),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0C000000[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 300),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BILLBOARD(),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0500B188),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -243, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 488, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0500AD08),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD(),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0500A5D8),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bob_dl_0500B2D0),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0500B418),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0500B6C0),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 243, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 488, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0500B068),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD(),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0500A890),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -1, 36, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 548, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD(),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0500A4F0),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 189, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_BILLBOARD(),
                                        GEO_OPEN_NODE(),
                                            GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0500A6C0),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                    GEO_ASM(0, geo_update_projectile_pos_from_parent),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 1, 36, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 548, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD(),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0500A7A8),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 189, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_BILLBOARD(),
                                        GEO_OPEN_NODE(),
                                            GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0500A978),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_12000440[] = {
    GEO_CULLING_RADIUS(1000),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0700E458),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_12000458[] = {
    GEO_CULLING_RADIUS(1200),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_0700E768),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_12000470[] = {
    GEO_CULLING_RADIUS(800),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0700E8A0),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
