const GeoLayout thi_area_1_geo_0E000608[] = {
    GEO_NODE_SCREEN_AREA(10, 160, 120, 160, 120),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND(0x0000, geo_skybox_main),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM_WITH_FUNC(45, 100, 20000, geo_camera_fov),
            GEO_OPEN_NODE(),
                GEO_CAMERA(1, 0, 2000, 6000, 0, 0, 0, geo_camera_main),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, thi_area_1_dl_07005260),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, thi_area_1_dl_07006968),
                    GEO_DISPLAY_LIST(LAYER_ALPHA, thi_area_1_dl_07007008),
                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, thi_area_1_dl_070072E8),
                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, thi_area_1_dl_070073C0),
                    GEO_ASM(0, geo_movtex_pause_control),
                    GEO_ASM(4865, geo_movtex_draw_water_regions),
                    GEO_RENDER_OBJ(),
                    GEO_ASM(0, geo_envfx_main),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_cannon_circle_base),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
