const GeoLayout bob_geo_0C000308[] = {
    GEO_CULLING_RADIUS(150),
    GEO_OPEN_NODE(),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bob_dl_05011000),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0C000328[] = {
    GEO_CULLING_RADIUS(150),
    GEO_OPEN_NODE(),
        GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 100, 160),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0C000000[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 300),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BILLBOARD(),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0500B188),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -243, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 488, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0500AD08),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD(),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0500A5D8),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bob_dl_0500B2D0),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0500B418),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0500B6C0),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 243, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 488, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0500B068),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD(),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0500A890),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -1, 36, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 548, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD(),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0500A4F0),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 189, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_BILLBOARD(),
                                        GEO_OPEN_NODE(),
                                            GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0500A6C0),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                    GEO_ASM(0, geo_update_projectile_pos_from_parent),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 1, 36, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 548, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD(),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0500A7A8),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 189, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_BILLBOARD(),
                                        GEO_OPEN_NODE(),
                                            GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0500A978),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D000358[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 155, 200),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 14, 3, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_06015850),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 46, 0, 0, bob_dl_06016F20),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 154, 0, 0, bob_dl_06016D98),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 153, 0, 0, bob_dl_06016C10),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 236, 42, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_060160B0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_06016120),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 217, -2, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_060169E8),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_06016A78),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 49, 0, -34, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bob_dl_06015480),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 49, 0, 37, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bob_dl_06015578),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D000480[] = {
    GEO_CULLING_RADIUS(2000),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_NODE(LAYER_FORCE, 0, 0, -50),
        GEO_OPEN_NODE(),
            GEO_SHADOW(51, 180, 0),
            GEO_OPEN_NODE(),
                GEO_SCALE(LAYER_FORCE, 0x00004000),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0601F5E0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, -12, 490, -5, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0601FEA8),
                            GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, -18, -479, -5, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_06020038),
                            GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 1075, 570, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0601F880),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_ALPHA, 400, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_BILLBOARD(),
                                        GEO_OPEN_NODE(),
                                            GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0601FBC0),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 1068, -574, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0601FAE8),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_ALPHA, 400, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_BILLBOARD(),
                                        GEO_OPEN_NODE(),
                                            GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0601FCA8),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D000214[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 155, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_06008250),
                GEO_OPEN_NODE(),
                    GEO_SWITCH_CASE(2, geo_switch_anim_state),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 114, 0, 0, bob_dl_06007AF8),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 114, 0, 0, bob_dl_06007B20),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -29, 39, 60, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0600B838),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, bob_dl_060086D0),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -29, 39, -60, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0600BA10),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, bob_dl_06008B50),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 55, 25, -73, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0600BC18),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, bob_dl_0600BA90),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 55, 25, 74, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0600BE10),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, bob_dl_0600BC88),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D0000D0[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 155, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0600C498),
                GEO_OPEN_NODE(),
                    GEO_SWITCH_CASE(2, geo_switch_anim_state),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 114, 0, 0, bob_dl_06007AF8),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 114, 0, 0, bob_dl_06007B20),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -29, 39, 60, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0600B838),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, bob_dl_060086D0),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, -29, 39, -60, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0600BA10),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, bob_dl_06008B50),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 55, 25, -73, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0600BC18),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, bob_dl_0600BA90),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 55, 25, 74, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_0600BE10),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, bob_dl_0600BC88),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D0005D0[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 60),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_060212E8),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D0005EC[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 200),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_06024940),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_06024FC0),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_06024240),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_06024D60),
                GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bob_dl_06024B00),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D000000[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_06000A08),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 2040, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bob_dl_06000B08),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 460, 0, 0, bob_dl_06000BF8),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 460, 0, 0, bob_dl_06000CE0),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 344, 0, 0, bob_dl_06000DB0),
                                    GEO_OPEN_NODE(),
                                        GEO_ANIMATED_PART(LAYER_OPAQUE, 288, 0, 0, bob_dl_06000E38),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D0000B8[] = {
    GEO_CULLING_RADIUS(450),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_06002410),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_16000FE8[] = {
    GEO_CULLING_RADIUS(800),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_0302FEE8),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
