extern const GeoLayout eggcolor_3_geo[];
extern Lights1 eggcolor_3_Fast3D_Material_003_lights;
extern u8 eggcolor_3_transparent_star_geo_0x606c10_custom_rgba16_ci8[];
extern u8 eggcolor_3_transparent_star_geo_0x606c10_custom_rgba16_pal_rgba16[];
extern Vtx eggcolor_3_eggcolor_3_mesh_layer_1_vtx_cull[8];
extern Vtx eggcolor_3_eggcolor_3_mesh_layer_1_vtx_0[70];
extern Gfx eggcolor_3_eggcolor_3_mesh_layer_1_tri_0[];
extern Gfx mat_eggcolor_3_Fast3D_Material_003[];
extern Gfx mat_revert_eggcolor_3_Fast3D_Material_003[];
extern Gfx eggcolor_3_eggcolor_3_mesh_layer_1[];
